# Arrays

An array is a type of data structure that stores elements of the same type in a contiguous block of memory. In an array, , of size , each memory location has some unique index,  (where ), that can be referenced as  or .

### Table of Content

 
1) <a href='#01'>Reverse Array</a>

2) <a href='#02'>2D Array</a>

3) <a href='#03'>Dynamic Array</a>

4) <a href='#04'>Two Sum Array</a>

5) <a href='#05'>Remove Duplicates from Sorted Array</a>

6) <a href='#06'>Remove Element</a>

7) <a href='#07'>Search Insert Position</a>

8) <a href='#08'>Plus One</a>

9) <a href='#09'>Merge Sorted Array</a>

10) <a href='#10'>Convert Sorted Array to Binary Search 10ee</a>

11) <a href='#11'>Max Profit share sell and buy</a>

12) <a href='#12'>Contains Duplicate</a> 

13) <a href='#13'>Single Numbe</a>

14) <a href='#14'>Summary Ranges</a>

15) <a href='#15'>Pascal's Triangle</a>

16) <a href='#16'>Richest Customer Wealth</a>

## <a id='01'>Reverse Array</a>

In [1]:
def reverseArray(a):
    l = []
    for i in a[::-1]:
        l.append(i)
    return l

In [2]:
A=[3,2,5,8,7]
reverseArray(A)


[7, 8, 5, 2, 3]

In [3]:
print(type(reverseArray(A)))

<class 'list'>


## <a id='02'>2D Array</a>

In [4]:
import numpy as np

In [5]:
Arr = np.array([[1,2,5,6,6,0],[0,5,6,8,5,0],[2,0,2,0,5,0],
      [0,5,6,8,5,0],[8,5,9,2,5,-8],[-5,-9,0,-8,2,7]])

print(Arr)
print("Array size having this shape:::")
print(Arr.shape)


[[ 1  2  5  6  6  0]
 [ 0  5  6  8  5  0]
 [ 2  0  2  0  5  0]
 [ 0  5  6  8  5  0]
 [ 8  5  9  2  5 -8]
 [-5 -9  0 -8  2  7]]
Array size having this shape:::
(6, 6)


In [6]:
def hourglassSum(arr):
    max = -float('inf')
    for i in range(1,(len(arr)-1)):
        for j in range(1,(len(arr)-1)):
            sum=0
            sum+= arr[i][j]
            sum+= arr[i-1][j-1]+arr[i-1][j]+arr[i-1][j+1]
            sum+= arr[i+1][j-1]+arr[i+1][j]+arr[i+1][j+1]
            
            if sum>max:
                max=sum
    return max


In [7]:
hourglassSum(Arr)

40

In [8]:
a = np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

 <a id='the_destination'>Shubham</a>

In [9]:
hourglassSum(a)

196

In [10]:
rg = np.random.random_integers(-30,30,36)

C:\Users\ShubhamSurya_2m9wvm4\AppData\Local\Temp\ipykernel_6948\2427472980.py:1: DeprecationWarning: This function is deprecated. Please call randint(-30, 30 + 1) instead
  rg = np.random.random_integers(-30,30,36)


In [11]:
rg

array([-12, -16,   0, -14,   7,  -6,  18,  -6,  26, -15,  24,  28,  17,
        17,  14,  24,  -5,  18,  -8, -28, -28,  27,  12, -30,   0,  28,
        -2, -14,   2,  22, -18,  -8,  14,  28, -19,  17])

In [12]:
len(rg)

36

In [13]:
a = rg.reshape(6,6)
a

array([[-12, -16,   0, -14,   7,  -6],
       [ 18,  -6,  26, -15,  24,  28],
       [ 17,  17,  14,  24,  -5,  18],
       [ -8, -28, -28,  27,  12, -30],
       [  0,  28,  -2, -14,   2,  22],
       [-18,  -8,  14,  28, -19,  17]])

In [14]:
hourglassSum(a)

70

In [15]:
type(rg)

numpy.ndarray

## <a id='03'>Dynamic Array</a>

## <a id='04'>Two Sum Array</a>

In [32]:
def twoSum(List,target):
    ls=[]
    for i in range(len(List)):
        for j in range(1,len(List)):
            if List[i]+List[j]==target:
                ls.append(i)
#                 ls.append(j)
    return ls

List=[2,1,5,3]
target=4
a = twoSum(List,target)
a

[1, 3]

## HashMap

In [35]:
def twoSum(nums, target):
    preMap={}      
    for i, n in enumerate(nums):
        diff = target - n
        if diff in preMap:
            return [preMap[diff], i]
        preMap[n] = i
        
nums=[2,1,5,3]
target=4
a = twoSum(nums,target)
a

[1, 3]

In [55]:
lst=[2,1,5,3]
mydict={}
target=4
for i,v in enumerate(lst):
    diff = target - v
    if diff in mydict:
        print("Answer : ",[mydict[diff], i])
    else:
        mydict[diff] = i
print(mydict)

{2: 0, 3: 1, -1: 2, 1: 3}


## <a id='#03'>Remove Duplicates from Sorted Array</a>

In [68]:
List = [0,0,1,1,1,2,2,3,3,4]
unique = []
def rmdup(List):
    for i in List:
        if i not in unique:
            unique.append(i)
    return len(unique)
a=rmdup(List)
a

5

In [67]:
def removeDuplicates(List):
    size = len(List)
    insertIndex = 1
    for i in range(1,size):
        if List[i-1] != List[i]:
            List[insertIndex] = List[i]
#             print(insertIndex)
            insertIndex += 1
        i += 1
    return insertIndex

l=[0,0,1,1,1,2,2,3,3,4]
b= removeDuplicates(l)
b

5

## <a id='06'> Remove Element </a>

In [5]:
def removeEle(lst,val):
    while val in lst:
        print( val)
        lst.remove(val)
    return len(lst)
            
nums = [3,2,2,3]
val = 3 
c = removeEle(nums,val)
c

3
3


2

## <a id='07'> Search Insert Position </a>


Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

Example 1:

Input: nums = [1,3,5,6], target = 5
Output: 2

Example 2:

Input: nums = [1,3,5,6], target = 2
Output: 1

In [5]:
def searchinsert(List,target):
    n = len(List)
    left = 0
    right = n-1
    while left <= right:
        mid = (left+right)//2
        if List[mid]==target:
            return "find position"
        elif List[mid] < target:
            left = mid+1
        else:
            right = mid -1
    return left


List=[1,3,5,6]
target = 2

s = searchinsert(List,target)
s

1

## <a id='08'>Plus One </a>


In [17]:
digits = [4,3,2,1]
y=0
x=len(digits)
k=[]

for i in range(x):
  y+=digits[i]*pow(10,x-1)
  x-=1
y+=1

for i in str(y):
  k.append(int(i))
k  

[4, 3, 2, 2]

In [21]:
4*pow(10,3)

4000

In [22]:
3*pow(10,2)

300

In [23]:
2*pow(10,1)

20

In [24]:
2*pow(10,0)

2

## <a id='09'>Merge Sorted Array</a>


You are given two integer arrays nums1 and nums2, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively.

Merge nums1 and nums2 into a single array sorted in non-decreasing order.

The final sorted array should not be returned by the function, but instead be stored inside the array nums1. To accommodate this, nums1 has a length of m + n, where the first m elements denote the elements that should be merged, and the last n elements are set to 0 and should be ignored. nums2 has a length of n.

 

Example 1:

Input: nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
Output: [1,2,2,3,5,6]
Explanation: The arrays we are merging are [1,2,3] and [2,5,6].
The result of the merge is [1,2,2,3,5,6] with the underlined elements coming from nums1.
Example 2:

Input: nums1 = [1], m = 1, nums2 = [], n = 0
Output: [1]
Explanation: The arrays we are merging are [1] and [].
The result of the merge is [1].

## <a id='10'>Convert Sorted Array to Binary Search Tree</a>

In [18]:
# Definition for a binary tree node.
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right
    def sortedArrayToBST(nums):    
        def helper(l,r):
            if l>r:
                return None
            m = (l+r)//2
            root = TreeNode(nums[m])
            root.left = helper(l,m-1)
            root.right = helper(m+1,r)
            return root
        return helper(0,len(nums)-1)
    
    def print_tree(self):
        elements=[]
        #visit left tree
        if self.left:
            elements += self.left.print_tree()
        #visit base data
        elements.append(self.val)
        
        #visit right tree
        if self.right:
            elements += self.right.print_tree()
        return elements
    
            
        

In [19]:
# sol= Solution.sortedArrayToBST([-10,-3,0,5,9])

In [20]:
lst=[-10,-3,0,5,9]

In [21]:
sol = TreeNode.sortedArrayToBST(lst)

In [22]:
sol.print_tree()

[-10, -3, 0, 5, 9]

In [15]:
# Definition for a binarySearchtree node.
class TreeNode:
    def __init__(self, data=0, left=None, right=None):
        self.data = data
        self.left = left
        self.right = right
        
    def add_child(self, data):
        if data == self.data:
            return
        if data < self.data:
            if self.left:
                self.left.add_child(data)
            else:
                self.left = TreeNode(data)
        else:
            if self.right:
                self.right.add_child(data)
            else:
                self.right = TreeNode(data)
                
    def in_order_traversal(self):
        elements=[]
        #visit left tree
        if self.left:
            elements += self.left.in_order_traversal()
            
        #visit base data
        elements.append(self.data)
        #visit Right tree
        if self.right:
            elements += self.right.in_order_traversal()
        
        return elements
            
    def build_Tree(elements):
        root = TreeNode(elements[0])

        for i in range(1,len(elements)):
            root.add_child(elements[i])
        return root
if __name__ == '__main__':
    numbers = [17,4,1,20,9,23,18,34]
    number_tree = build_Tree(numbers)
    print(number_tree.in_order_traversal())

[1, 4, 9, 17, 18, 20, 23, 34]


In [10]:
prices = [7,1,5,3,6,4]
print(min(prices))
print(max(prices))

1
7


In [14]:
# index(element, start, end)
prices.index(6)

4

## <a id='11'>Find max Profit</a>

In [4]:
def maxProfit(prices): 
    left = 0 #Buy
    right = 1 #Sell
    max_profit = 0
    while right < len(prices):
        currentProfit = prices[right] - prices[left] #our current Profit
        print("kdhsk",currentProfit)
        if prices[left] < prices[right]:
            max_profit =max(currentProfit,max_profit)
            print(max_profit)
        else:
            left = right
        right += 1
    return max_profit


        
prices = [7,1,5,3,6,4]        
s= maxProfit(prices)
s

kdhsk -6
kdhsk 4
4
kdhsk 2
4
kdhsk 5
5
kdhsk 3
5


5

## <a id='12'>Contains Duplicate</a>


In [2]:
def containsDuplicate(self, nums: List[int]) -> bool:
    
        window_start = 0

        num_freq = {}

        for window_end in range(len(nums)):
            current = nums[window_end]

            if current not in num_freq:
                num_freq[current] = 1

            else:
                return True

        return False

NameError: name 'List' is not defined

In [9]:
def containsDuplicate(nums):
    lst=[]
    for i in range(len(nums)):
        if nums[i] in lst:
            return True
        else:
  
nums = [1,2,3,1]
s= containsDuplicate(nums)

IndentationError: expected an indented block (565350296.py, line 8)

In [10]:
## resursion

def fobi(num):
    if num==1:
        return 1
    return num+fobi(num-1)
    


In [11]:
s = fobi(4)
s

10

In [13]:
l=[9]
if len(l)==1:
    print(l)

[9]



## <a id='13'>Single Number</a>

In [25]:
class Solution(object):
   def singleNumber(self, nums):
      """
      :type nums: List[int]
      :rtype: int
      """
      ans = nums[0]
      for i in range(1,len(nums)):
         ans ^=nums[i]
      return ans
ob1 = Solution()

print(ob1.singleNumber([1,1,5,3,2,5,2]))

3


In [22]:
def singlenumber(nums):
    sino=None
    for i,v in enumerate(nums):
        
    return sino      
nums = [2,2,1]
sn=singlenumber(nums)
sn       

2

## <a id='14'>Summary Ranges</a> 

In [27]:
nums = [0,2,3,4,6,8,9]

i=0
result=[]
if (len(nums)==0):
    print(None)
while (i < len(nums)):
    j=i+1
    while (j<len(nums)):
        if (nums[j-1]+1==nums[j]):
            j+=1
        else:
            break
    if (j-i==1):
        result.append(str(nums[i]))
    else:
        result.append(str(nums[i])+'->'+str(nums[j-1]))
    i=j
print(result)


['0', '2->4', '6', '8->9']


## <a id='15'>Pascal's Triangle</a>

In [24]:
numRows=4
res = [[1], [1,1]]
if numRows == 1:
    print([[1]])
elif numRows == 2:
    print(res)

for i in range(1, (numRows-1)):
    l, r = 0,1
    cand = [1]
    while r < len(res[i]):
        cand.append(res[i][l] + res[i][r])
        l += 1
        r += 1
    cand.append(1) 
    res.append(cand)

print(res)

[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1]]


## <a id='16'>Richest Customer Wealth</a>

In [5]:
accounts = [[2,8,7],[7,1,3],[1,9,5]]
welths=[]
for i in accounts:
    count=0
    for j in i:
        count+=j
    welths.append(count)
max(welths)

17